"use strict";
/* ============ SET: HEX & RELIC ============
   Interaction set: hexes that cripple the enemy, relics that transform your
   own units, and envelope-pushing sorcery (ownership swaps, stat inversion,
   mirrors, the Leveller). Also introduces POWERED UNITS — units that charge
   ⚡1 per turn in play and carry a spell of their own.
   Design laws hold: every card works in both dimensions; new cards are data. */

const HEXRELIC = {
  /* ---------------- HEXES · enemy-affecting spells ---------------- */
  hx_frost:   {rarity:"rare", name:"Grasp of Frost", cost:2, type:"spell", target:"enemyLiving", fx:{kind:"freeze", n:2},
    text:"Freeze an enemy living unit for 2 turns — it cannot wake.",
    deadFace:{name:"Grave Chill", target:"enemyDead", fx:{kind:"freeze", n:2}, text:"Freeze an enemy dead unit for 2 turns."},
    art:{l:"a knight seized mid-swing by creeping blue hoarfrost, breath hanging frozen",
         d:"a spectral hand of ice closing around a shrieking ghost, frost blooming across the void"}},
  hx_blight:  {rarity:"common", name:"Creeping Blight", cost:1, type:"spell", target:"enemyLiving", fx:{kind:"blight", n:1},
    text:"Blight an enemy living unit: it takes 1 damage at the start of each of its owner's turns, forever.",
    deadFace:{name:"Soul Rot", target:"enemyDead", fx:{kind:"blight", n:1}, text:"Rot an enemy dead unit: 1 damage at the start of each of its owner's turns, forever."},
    art:{l:"black-green mould spreading up a soldier's arm as he stares in horror",
         d:"luminous violet rot eating holes through a translucent spirit"}},
  hx_toadhex: {rarity:"epic", name:"Croaking Curse", cost:3, type:"spell", target:"enemyLiving", fx:{kind:"transform", into:"toad"},
    text:"Transform an enemy living unit into a 1/1 Toad.",
    deadFace:{name:"Wisp Curse", target:"enemyDead", fx:{kind:"transform", into:"toad"}, text:"Transform an enemy dead unit into a 1/1 Ghost Toad."},
    art:{l:"a proud knight mid-transformation into a fat warty toad, armor clattering empty",
         d:"a fearsome wraith deflating into a tiny glowing ghost toad, confused"}},
  hx_hollow:  {rarity:"rare", name:"Hollowing", cost:2, type:"spell", target:"enemyLiving", fx:{kind:"hollow"},
    text:"Hollow an enemy living unit: it loses all abilities and gifts.",
    deadFace:{name:"Deeper Hollowing", target:"enemyDead", fx:{kind:"hollow"}, text:"Hollow an enemy dead unit: it loses all abilities and gifts."},
    art:{l:"a warrior whose eyes turn to smooth grey stone, banner slipping from his hand",
         d:"a ghost unravelling into blank white mist, its crown dissolving"}},
  hx_shackle: {rarity:"common", name:"Leaden Shackles", cost:1, type:"spell", target:"enemyLiving", fx:{kind:"shackle"},
    text:"Shackle an enemy living unit: it can never strike your hero, only units.",
    deadFace:{name:"Soul Irons", target:"enemyDead", fx:{kind:"shackle"}, text:"Iron an enemy dead unit: it can never strike your hero, only units."},
    art:{l:"massive black chains erupting from the earth to bind a berserker's legs",
         d:"glowing violet manacles clamping onto a spirit's wrists, runes burning"}},
  hx_mark:    {rarity:"epic", name:"Mark of the Reaper", cost:4, type:"spell", target:"enemyLiving", fx:{kind:"markdoom", t:2},
    text:"Mark an enemy living unit: in 2 turns, it dies. Nothing lifts the mark.",
    deadFace:{name:"Second Marking", target:"enemyDead", fx:{kind:"markdoom", t:2}, text:"Mark an enemy dead unit: in 2 turns, it is destroyed. Nothing lifts the mark."},
    art:{l:"a glowing black sigil burning itself onto a champion's forehead, scythe shadow behind",
         d:"a skeletal finger drawing a second darker sigil over a spirit already marked once"}},
  hx_betray:  {rarity:"rare", name:"Whispered Betrayal", cost:3, type:"spell", target:"enemyLiving", fx:{kind:"betray"},
    text:"An enemy living unit hears the whisper and deals its ATK to its weakest ally.",
    deadFace:{name:"Grave Whispers", target:"enemyDead", fx:{kind:"betray"}, text:"An enemy dead unit turns and deals its ATK to its weakest ally."},
    art:{l:"a soldier with wild eyes turning his sword on his own shieldmate, a shadowy mouth at his ear",
         d:"one ghost strangling another while a third whispers from the dark"}},
  hx_winter:  {rarity:"legendary", name:"Winterveil", cost:5, type:"spell", fx:{kind:"freezeAll", n:1},
    text:"Winter takes the living dimension: freeze ALL enemy living units for 1 turn.",
    deadFace:{name:"The Long Winter", fx:{kind:"freezeAll", n:1}, text:"Winter crosses over: freeze ALL enemy dead units for 1 turn."},
    art:{l:"a wall of blizzard rolling over an army, soldiers frozen mid-charge like statues",
         d:"an entire ghostly legion locked in blue ice beneath a black aurora"}},
  hx_gale:    {rarity:"rare", name:"Banishing Gale", cost:2, type:"spell", target:"enemyLiving", fx:{kind:"bounce"},
    text:"Blow an enemy living unit back into its owner's hand.",
    deadFace:{name:"Sighing Gale", target:"enemyDead", fx:{kind:"bounce"}, text:"Blow an enemy dead unit back into its owner's dead hand."},
    art:{l:"a screaming gale ripping a warrior off his feet, cloak and sword flying",
         d:"a spectral wind unravelling a ghost into ribbons that stream away"}},

  /* ---------------- RELICS · charms for your own units ---------------- */
  hx_fangs:   {rarity:"rare", name:"Vampire Fangs", cost:2, type:"spell", target:"friendlyLiving", fx:{kind:"grant", what:"lifesteal", label:"Lifesteal"},
    text:"A friendly living unit gains Lifesteal: its strikes restore that much Life.",
    deadFace:{name:"Soul Fangs", target:"friendlyDeadAny", fx:{kind:"grant", what:"lifesteal", label:"Lifesteal"}, text:"A friendly dead unit gains Lifesteal: its strikes restore that much Soul."},
    art:{l:"a warrior baring new-grown fangs, a bitten apple of red light in his fist",
         d:"a ghost with long crystal fangs drinking a stream of silver light"}},
  hx_bow:     {rarity:"rare", name:"Spectral Longbow", cost:2, type:"spell", target:"friendlyLiving", fx:{kind:"grant", what:"ranged", label:"Ranged"},
    text:"A friendly living unit gains Ranged: no retaliation when it attacks.",
    deadFace:{name:"Wraithstring", target:"friendlyDeadAny", fx:{kind:"grant", what:"ranged", label:"Ranged"}, text:"A friendly dead unit gains Ranged: no retaliation when it attacks."},
    art:{l:"a glowing translucent longbow settling into a soldier's grip, arrows of light",
         d:"a bow strung with a howling wisp, drawn by skeletal fingers"}},
  hx_plate:   {rarity:"common", name:"Gravewrought Plate", cost:2, type:"spell", target:"friendlyLiving", fx:{kind:"fortify", n:2},
    text:"A friendly living unit gains +2 HP and Guard.",
    deadFace:{name:"Casket Iron", target:"friendlyDeadAny", fx:{kind:"fortify", n:2}, text:"A friendly dead unit gains +2 HP and Guard."},
    art:{l:"black iron plates hammered from coffin nails locking around a fighter's chest",
         d:"a ghost armored in floating shards of casket iron, violet light in the seams"}},
  hx_horn:    {rarity:"epic", name:"Horn of Twin Blows", cost:3, type:"spell", target:"friendlyLiving", fx:{kind:"grant", what:"doubleStrike", label:"Twin Strike"},
    text:"A friendly living unit gains Twin Strike: it may attack twice each turn.",
    deadFace:{name:"Echoing Horn", target:"friendlyDeadAny", fx:{kind:"grant", what:"doubleStrike", label:"Twin Strike"}, text:"A friendly dead unit gains Twin Strike: it may attack twice each turn."},
    art:{l:"a warhorn splitting one knight into two overlapping after-images mid-swing",
         d:"a bone horn whose note splits a spirit into twin echoes"}},
  hx_quick:   {rarity:"common", name:"Quicksilver Charm", cost:1, type:"spell", echo:true, target:"friendlyLiving", fx:{kind:"ready"},
    text:"Ready a friendly living unit (it may act again). Echo: the cast slips into your dead hand.",
    deadFace:{name:"Stillsilver Charm", target:"friendlyDeadAny", fx:{kind:"ready"}, text:"Ready a friendly dead unit (it may act again)."},
    art:{l:"a vial of living quicksilver splashing across a swordsman who blurs with speed",
         d:"drops of frozen silver light orbiting a ghost that moves between moments"}},
  hx_giant:   {rarity:"common", name:"Giant's Blood", cost:3, type:"spell", target:"friendlyLiving", fx:{kind:"buff", a:2, h:2},
    text:"A friendly living unit drinks deep: +2/+2.",
    deadFace:{name:"Titan's Ash", target:"friendlyDeadAny", fx:{kind:"buff", a:2, h:2}, text:"A friendly dead unit is dusted with titan's ash: +2/+2."},
    art:{l:"a soldier drinking from a huge horn, veins glowing gold, growing a head taller",
         d:"a ghost inhaling a swirl of grey ash and swelling into something vast"}},

  /* ---------------- ENVELOPE-PUSHERS ---------------- */
  hx_invert:  {rarity:"rare", name:"Inversion Hex", cost:2, type:"spell", target:"anyLiving", fx:{kind:"invert"},
    text:"Swap a living unit's ATK and HP. Yours or theirs.",
    deadFace:{name:"Mirror Hex", target:"anyDead", fx:{kind:"invert"}, text:"Swap a dead unit's ATK and HP. Yours or theirs."},
    art:{l:"a warrior reflected upside-down in a rippling mirror, sword and heart trading places",
         d:"a ghost turning itself inside out through a ring of violet glass"}},
  hx_mirror:  {rarity:"epic", name:"Mirror of Bone", cost:4, type:"spell", target:"anyLiving", fx:{kind:"clone"},
    text:"Summon a fresh copy of ANY living unit — even theirs — on your side.",
    deadFace:{name:"Mirror of Mist", target:"anyDead", fx:{kind:"clone"}, text:"Summon a fresh copy of ANY dead unit — even theirs — on your side."},
    art:{l:"a full-length mirror framed in vertebrae, a second identical knight stepping out of it",
         d:"a mirror of still fog birthing a duplicate ghost, both staring at each other"}},
  hx_exchange:{rarity:"epic", name:"Soul Exchange", cost:4, type:"spell", target:"enemyLiving", fx:{kind:"swap"},
    text:"Trade your weakest living unit for an enemy living unit. A pact is a pact.",
    deadFace:{name:"Grave Bargain", target:"enemyDead", fx:{kind:"swap"}, text:"Trade your weakest dead unit for an enemy dead unit."},
    art:{l:"two armies watching a peasant and an armored champion walk past each other across a chalk line",
         d:"two ghosts passing through each other mid-trade, chains of contract-script linking them"}},
  hx_leveller:{rarity:"legendary", name:"The Leveller", cost:6, type:"spell", fx:{kind:"equalize"},
    text:"EVERY living unit becomes 3/3. No more, no less. The Leveller does not negotiate.",
    deadFace:{name:"The Leveller's Shadow", fx:{kind:"equalize"}, text:"EVERY dead unit becomes 3/3. No more, no less."},
    art:{l:"a colossal stone scale descending from storm clouds over a battlefield, armies shrinking and growing to equal size",
         d:"a shadowy scale weighing two rows of identical ghosts in perfect balance"}},
  hx_robbery: {rarity:"rare", name:"Grave Robbery", cost:2, type:"spell", fx:{kind:"stealDeadHand"},
    text:"Steal a random card from the enemy's dead hand into yours.",
    deadFace:{name:"Tomb Heist", fx:{kind:"stealDeadHand"}, text:"Steal a random card from the enemy's dead hand into yours."},
    art:{l:"a grinning thief climbing out of someone else's grave clutching a glowing card",
         d:"a spectral hand reaching through a wall of mist into a rival's coffin-hoard"}},
  hx_sunrise: {rarity:"legendary", name:"Second Sunrise", cost:6, type:"spell", fx:{kind:"massReady"},
    text:"Ready ALL your living units. The day refuses to end.",
    deadFace:{name:"Endless Midnight", fx:{kind:"massReady"}, text:"Ready ALL your dead units. The night refuses to end."},
    art:{l:"a second sun tearing over the horizon mid-battle, an exhausted army rising golden and renewed",
         d:"a black sun rising over a ghost legion, every spirit reigniting violet"}},

  /* ---------------- POWERED UNITS · they charge ⚡ in play ---------------- */
  hx_pyro:    {rarity:"rare", name:"Hedge Pyromancer", deadName:"Ember Shade", cost:3, type:"unit", l:[2,3], d:[2,2],
    power:{name:"Firebolt", cost:2, kind:"boltFoe", n:2, text:"⚡2: deal 2 damage to the strongest enemy unit in its dimension (or the enemy hero)."},
    text:"Charges ⚡1 per turn. Firebolt (⚡2): 2 damage to the strongest enemy in its dimension.",
    art:{l:"a scruffy hedge wizard juggling a fistful of sputtering fire, singed robes",
         d:"a shade of cooled embers, one hand still burning with pale fire"}},
  hx_chanter: {rarity:"epic", name:"Bone Chanter", deadName:"Choir of Marrow", cost:4, type:"unit", l:[2,4], d:[3,3],
    power:{name:"Dirge of Hunger", cost:3, kind:"drainSoul", n:2, text:"⚡3: drain 2 Soul from the enemy (Life if shattered)."},
    text:"Charges ⚡1 per turn. Dirge of Hunger (⚡3): drain 2 enemy Soul.",
    art:{l:"a robed chanter rattling a necklace of knucklebones, sound waves bending the air",
         d:"a choir of jawbones floating in a circle, singing without lungs"}},
  hx_oracle:  {rarity:"epic", name:"Veil Oracle", deadName:"Oracle Unblinded", cost:4, type:"unit", l:[1,5], d:[2,4],
    power:{name:"Scry", cost:2, kind:"draw", n:1, text:"⚡2: draw a card."},
    text:"Charges ⚡1 per turn. Scry (⚡2): draw a card.",
    art:{l:"a blindfolded seer with a bowl of black water reflecting cards that do not exist yet",
         d:"the same seer with the blindfold gone, sockets full of tiny galaxies"}},
  hx_idol:    {rarity:"legendary", name:"Storm Idol", deadName:"Silent Idol", cost:6, type:"unit", l:[3,6], d:[4,5],
    power:{name:"Tempest", cost:4, kind:"stormFoes", n:1, text:"⚡4: deal 1 damage to EVERY enemy unit in both dimensions."},
    text:"Charges ⚡1 per turn. Tempest (⚡4): 1 damage to every enemy unit, everywhere.",
    art:{l:"a squat stone idol crackling with caged lightning, monks prostrate around it",
         d:"the idol cracked open and hollow, a quiet storm turning inside"}},
  hx_saint:   {rarity:"rare", name:"Banner Saint", deadName:"Martyr's Standard", cost:3, type:"unit", l:[2,3], d:[2,3],
    power:{name:"Rally", cost:3, kind:"rallyAllies", n:1, text:"⚡3: your OTHER units in its dimension gain +1 ATK permanently."},
    text:"Charges ⚡1 per turn. Rally (⚡3): +1 ATK to your other units in its dimension.",
    art:{l:"a young standard-bearer holding a torn banner high while soldiers rise behind her",
         d:"the banner itself, planted and glowing, ghosts kneeling in its light"}},

  /* ---------------- HEX UNITS · debuffs on play ---------------- */
  hx_witch:   {rarity:"rare", name:"Gutter Witch", deadName:"Gutter Haunt", cost:3, type:"unit", l:[2,3], d:[3,2], ability:"weaken2",
    text:"On play: the strongest enemy unit in its dimension loses 2 ATK.",
    art:{l:"a crooked alley witch blowing grey powder off her palm toward a knight whose sword droops",
         d:"a haunt of rags and rat bones hexing a ghost whose claws crumble"}},
  hx_wight:   {rarity:"epic", name:"Frost Wight", deadName:"Deepfrost Wight", cost:4, type:"unit", l:[3,4], d:[3,3], ability:"freezer",
    text:"On play: freeze the strongest enemy unit in its dimension for 1 turn.",
    art:{l:"a blue-skinned wight exhaling a cone of hoarfrost that locks a warrior solid",
         d:"a deeper-blue wight whose breath freezes even other ghosts"}},
  hx_jailer:  {rarity:"common", name:"Veil Jailer", deadName:"Warden of Chains", cost:3, type:"unit", l:[2,4], d:[2,3], ability:"shackler",
    text:"On play: shackle the strongest enemy unit in its dimension — it cannot strike heroes.",
    art:{l:"a hulking jailer dragging a cart of black chains, keys of bone on his belt",
         d:"a spectral warden whose body is made of hanging chains and old locks"}},
  hx_countess:{rarity:"legendary", name:"Crimson Countess", deadName:"The Pale Countess", cost:5, type:"unit", l:[4,4], d:[4,4], lifesteal:true,
    text:"Lifesteal: her strikes restore that much Life (Soul among the dead).",
    art:{l:"an elegant countess in blood-red silk mid-waltz on a battlefield, lips parted",
         d:"the same countess bone-pale and translucent, drinking light from the air"}},

  /* ---------------- SITUATIONS · interactive auras ---------------- */
  hx_miasma:  {rarity:"epic", name:"Miasma of Despair", deadName:"Despair Eternal", cost:3, type:"situation",
    text:"Enemy LIVING units have −1 ATK.", sitFx:{kind:"foeLivingAtk", n:-1},
    deadFace:{name:"Despair Eternal", text:"Enemy DEAD units have −1 ATK.", sitFx:{kind:"foeDeadAtk", n:-1}},
    art:{l:"low grey-green fog rolling between soldiers whose shoulders slump, weapons dragging",
         d:"violet fog through which ghosts drift aimlessly, their fire dimmed"}},
  hx_nettles: {rarity:"rare", name:"Field of Nettles", deadName:"Wailing Nettles", cost:2, type:"situation",
    text:"At the start of your turn, sting the strongest enemy living unit for 1.", sitFx:{kind:"turnStingFoe", n:1},
    deadFace:{name:"Wailing Nettles", text:"At the start of your turn, sting the strongest enemy dead unit for 1.", sitFx:{kind:"turnStingFoe", n:1}},
    art:{l:"a battlefield overgrown with waist-high black nettles, a giant wincing knee-deep",
         d:"pale howling nettles that pass through armor and sting the soul beneath"}},
  hx_gallows: {rarity:"epic", name:"The Gallows", deadName:"Gallows of Souls", cost:4, type:"situation",
    text:"For 4 turns: the strongest enemy living unit loses 1 ATK at the start of your turn.", sitFx:{kind:"turnWeakenFoe", n:1, charges:4},
    deadFace:{name:"Gallows of Souls", text:"For 4 turns: the strongest enemy dead unit loses 1 ATK at the start of your turn.", sitFx:{kind:"turnWeakenFoe", n:1, charges:4}},
    art:{l:"an empty gallows on a hill that every soldier below refuses to look at",
         d:"a gallows of pale light from which nooses of mist hang into the ghost ranks"}},
  hx_forge:   {rarity:"rare", name:"Blood Forge", deadName:"Bone Forge", cost:3, type:"situation",
    text:"Your units enter the LIVING field with +1 ATK.", sitFx:{kind:"enterLivingAtk", n:1},
    deadFace:{name:"Bone Forge", text:"Your units enter the DEAD field with +1 ATK.", sitFx:{kind:"enterDeadAtk", n:1}},
    art:{l:"a forge fed with red-hot blood-iron, fresh recruits gripping still-glowing swords",
         d:"an anvil of vertebrae where skeletal smiths hammer edges onto ghost-blades"}},
};

Object.assign(DEFS, HEXRELIC);
