"use strict";
/* ============ VEILBOUND — 100-card expansion ============
   Novel mechanics:
   - Twin: on play (living), its reflection falls into your dead hand.
   - Harvest N: when this kills a unit, drain N Soul (Life if shattered).
   - Consume: on play (dead), eats the weakest friendly dead unit and gains its ATK.
   - Bloodprice N: costs N Life (living) / N Soul (dead — can shatter yourself) instead of energy.
   - Echo: cast from the living hand, a copy slips into your dead hand.
   - Veilshift: move your unit through the veil, swapping to its other face.
   - Gamble: reveal the top card — units storm in free, anything else falls to the dead hand.
   - Possess: steal an enemy dead unit. The dead answer whoever calls loudest.
   - Doom (knells): counts up each turn, then annihilates its whole dimension.
   - Charges: strong situations that burn out after N turns.
   Every card carries art:{l,d} prompts for the generator. */

const VEILBOUND = {
  /* ---------------- UNITS · commons ---------------- */
  vb_moth:     {rarity:"common", name:"Veilmoth", deadName:"Ashmoth", cost:1, type:"unit", l:[1,1], d:[2,1],
    text:"Drawn to the seam between worlds.",
    art:{l:"a large pale moth with tattered wings resting on a glowing seam of light in the dark",
         d:"a moth of grey ash and violet embers, wings crumbling as it flies"}},
  vb_urchin:   {rarity:"common", name:"Gutter Urchin", deadName:"Gutter Shade", cost:1, type:"unit", l:[2,1], d:[1,2],
    text:"Quick fingers, quicker feet.",
    art:{l:"a scrappy street urchin child in rags sprinting down a medieval alley at night",
         d:"a small hunched shadow of a child with pale eyes lurking in a flooded gutter"}},
  vb_toad:     {rarity:"common", name:"Marsh Toad", deadName:"Bloated Husk", cost:1, type:"unit", l:[1,2], d:[2,1],
    text:"Swallows anything smaller than regret.",
    art:{l:"a huge warty marsh toad half-submerged in black bog water, moonlight",
         d:"a bloated pale toad husk leaking faint green vapor, hollow eyes"}},
  vb_scarecrow:{rarity:"common", name:"Scarecrow", deadName:"Night Terror", cost:2, type:"unit", l:[0,4], d:[2,2], ability:"guard",
    text:"Guard: enemies in its dimension must attack this first.",
    art:{l:"a ragged scarecrow on a wooden cross in a moonlit wheat field, crows circling",
         d:"a scarecrow come alive with burning violet eyes, straw spilling like entrails"}},
  vb_shepherd: {rarity:"common", name:"Lost Shepherd", deadName:"Wandering Soul", cost:2, type:"unit", l:[2,2], d:[2,2],
    text:"Still counting a flock that is long gone.",
    art:{l:"a weary shepherd with a crook wandering a foggy moor, lantern in hand",
         d:"a translucent ghost of a shepherd drifting over the moor, lantern glowing blue"}},
  vb_gravemoss:{rarity:"common", name:"Gravemoss Crawler", deadName:"Moss Wight", cost:2, type:"unit", l:[1,3], d:[3,2],
    text:"It grows fastest on fresh stones.",
    art:{l:"a beetle-like creature covered in luminous green gravemoss crawling over headstones",
         d:"a humanoid wight made of moss and grave dirt, green light seeping from cracks"}},
  vb_torchboy: {rarity:"common", name:"Torchbearer Boy", deadName:"Willowisp", cost:2, type:"unit", l:[2,1], d:[2,1], ability:"haste",
    text:"Haste: attacks immediately, in either dimension.",
    art:{l:"a young torchbearer boy running with a blazing torch through a dark wood",
         d:"a flickering pale-blue willowisp flame darting between dead trees"}},
  vb_seamstress:{rarity:"common", name:"Shroud Seamstress", deadName:"Shroud Wraith", cost:2, type:"unit", l:[1,2], d:[1,2], ability:"twin",
    text:"Twin: on play (living), its reflection falls into your dead hand.",
    art:{l:"an old seamstress sewing a white burial shroud by candlelight, needle glinting",
         d:"a wraith wrapped in flowing burial shrouds, threads trailing into darkness"}},
  vb_bonepicker:{rarity:"common", name:"Bone Picker", deadName:"Marrow Thief", cost:2, type:"unit", l:[2,1], d:[1,2], ability:"digger",
    text:"On play: put the top card of your deck into your dead hand.",
    art:{l:"a stooped scavenger with a sack picking bones from a battlefield at dusk",
         d:"a gaunt ghoul cracking a bone for marrow, eyes glinting in the dark"}},
  vb_watchman: {rarity:"common", name:"Night Watchman", deadName:"Hollow Watch", cost:3, type:"unit", l:[1,5], d:[2,4], ability:"guard",
    text:"Guard: enemies in its dimension must attack this first.",
    art:{l:"a town watchman in a heavy coat holding a halberd and lantern at the gate",
         d:"an empty watchman's coat and helmet standing guard, nothing inside but mist"}},
  vb_butcher:  {rarity:"common", name:"Butcher of Wray", deadName:"Cleaver Shade", cost:3, type:"unit", l:[3,2], d:[2,3],
    text:"His scales always balanced in his favor.",
    art:{l:"a burly medieval butcher with a huge cleaver, blood-stained apron, grim face",
         d:"a shadow with a glowing cleaver drifting through a ruined market"}},
  vb_choirboy: {rarity:"common", name:"Choir Boy", deadName:"Silent Chorister", cost:1, type:"unit", l:[0,2], d:[1,1], ability:"heal2",
    text:"On play: restore 2 Life — or 2 Soul if played dead.",
    art:{l:"a young choir boy singing in a shaft of golden cathedral light",
         d:"a pale chorister with an open mouth and no sound, faint blue glow"}},
  vb_ratking:  {rarity:"common", name:"Rat King", deadName:"King of Bones", cost:3, type:"unit", l:[2,3], d:[3,2], ability:"rats",
    text:"On play: summon a 1/1 Rat in the same dimension.",
    art:{l:"a huge rat wearing a tiny tarnished crown atop a mound of squirming rats",
         d:"a skeletal rat king on a throne of tiny bones, violet eyes"}},
  vb_pilgrim:  {rarity:"common", name:"Veil Pilgrim", deadName:"Pilgrim's Echo", cost:2, type:"unit", l:[2,1], d:[1,1], ability:"twin",
    text:"Twin: on play (living), its reflection falls into your dead hand.",
    art:{l:"a hooded pilgrim with a walking staff approaching a shimmering tear in the air",
         d:"the after-image of a pilgrim repeated three times, fading into mist"}},
  vb_mule:     {rarity:"common", name:"Corpse Mule", deadName:"Skeletal Mule", cost:3, type:"unit", l:[2,4], d:[2,4],
    text:"Carries the dead. Eventually joins them.",
    art:{l:"a tired pack mule loaded with shrouded bodies on a mountain path",
         d:"a skeletal mule still carrying its shrouded burden, walking on"}},
  vb_fenlantern:{rarity:"common", name:"Fen Lantern", deadName:"Fen Light", cost:2, type:"unit", l:[1,3], d:[1,1], deadForm:"situation",
    text:"Its dead face is a situation — deploy it from your dead hand as an omen.",
    deadFace:{name:"Fen Light", text:"At the start of your turn, gain 1 dead energy.", sitFx:{kind:"turnDeadEss", n:1}},
    art:{l:"a lantern-keeper of the fens holding up a green-glass lamp over the marsh",
         d:"a disembodied green marsh light hovering over black water, faint faces inside"}},
  vb_cutpurse: {rarity:"common", name:"Cutpurse", deadName:"Fingers of Mist", cost:2, type:"unit", l:[2,1], d:[1,1], harvest:1,
    text:"Harvest 1: when this kills a unit, drain 1 Soul.",
    art:{l:"a masked cutpurse slicing a coin purse in a crowded plague-market",
         d:"ghostly disembodied hands of mist lifting a glowing soul like a coin purse"}},
  vb_boghag:   {rarity:"common", name:"Bog Hag", deadName:"Bog Revenant", cost:3, type:"unit", l:[3,3], d:[2,2],
    text:"She trades in teeth and promises.",
    art:{l:"a crooked bog hag stirring a cauldron of black water under willow trees",
         d:"a dripping revenant hag rising from the bog, weeds for hair"}},
  vb_thrall:   {rarity:"common", name:"Blood Thrall", deadName:"Pale Thrall", cost:0, blood:3, type:"unit", l:[2,2], d:[2,2],
    text:"Bloodprice 3: pay Life (living) or Soul (dead) instead of energy.",
    art:{l:"a gaunt thrall with red-glazed eyes and ritual cuts on his forearms",
         d:"a bone-white thrall with black veins kneeling before an unseen master"}},
  vb_beggar:   {rarity:"common", name:"Plague Beggar", deadName:"Weeping Thing", cost:1, type:"unit", l:[1,1], d:[1,1], ability:"plague",
    text:"On death: deal 1 damage to all enemy units in its dimension.",
    art:{l:"a shrouded beggar with a bell and bandaged hands sitting by a church door",
         d:"a small weeping creature of rags and sores, green haze around it"}},
  vb_carver:   {rarity:"common", name:"Totem Carver", deadName:"Totem Ghost", cost:3, type:"unit", l:[2,3], d:[3,3],
    text:"Every cut is a name remembered.",
    art:{l:"a woodcarver chiseling ancestor faces into a tall pine totem",
         d:"a ghost flowing out of a carved totem, the wooden faces screaming"}},
  vb_riverchild:{rarity:"common", name:"River Child", deadName:"River Ghost", cost:2, type:"unit", l:[2,2], d:[2,1], ability:"digger",
    text:"On play: put the top card of your deck into your dead hand.",
    art:{l:"a barefoot child skipping stones across a black glass river at dusk",
         d:"a small ghost sitting on the riverbed, hair drifting upward like weeds"}},
  vb_waxhusk:  {rarity:"common", name:"Wax Husk", deadName:"Melted Husk", cost:2, type:"unit", l:[0,5], d:[1,4],
    text:"A candle shaped like a man, or the other way round.",
    art:{l:"a man-shaped effigy of pale wax with a burning wick in its chest",
         d:"a half-melted wax figure slumped over, blue flame still burning"}},
  vb_dove:     {rarity:"common", name:"Grave Dove", deadName:"Ash Dove", cost:1, type:"unit", l:[1,1], d:[1,1], ability:"twin",
    text:"Twin: on play (living), its reflection falls into your dead hand.",
    art:{l:"a white dove perched on a cracked headstone, feather falling",
         d:"a dove of grey ash mid-flight, trailing embers"}},

  /* ---------------- UNITS · rares ---------------- */
  vb_duelist:  {rarity:"rare", name:"Veil Duelist", deadName:"Phantom Duelist", cost:3, type:"unit", l:[3,2], d:[2,2], harvest:1,
    text:"Harvest 1: when this kills a unit, drain 1 Soul.",
    art:{l:"a lean duelist with a thin blade saluting before a shimmering veil of light",
         d:"a translucent duelist mid-lunge, blade of pale light"}},
  vb_matron:   {rarity:"rare", name:"Crypt Matron", deadName:"Crypt Mother", cost:4, type:"unit", l:[2,6], d:[3,5], ability:"guard",
    text:"Guard: enemies in its dimension must attack this first.",
    art:{l:"a stern matron with a great iron key-ring standing before crypt doors",
         d:"a towering veiled mother figure of stone and shadow guarding a crypt"}},
  vb_chirurgeon:{rarity:"rare", name:"Chirurgeon", deadName:"Flesh Tailor", cost:3, type:"unit", l:[2,3], d:[2,2], ability:"heal2",
    text:"On play: restore 2 Life — or 2 Soul if played dead.",
    art:{l:"a plague-doctor chirurgeon with brass instruments and a leather apron",
         d:"a spindly tailor of flesh with needle fingers, stitching shadows"}},
  vb_twins:    {rarity:"rare", name:"The Parted Twins", deadName:"The Rejoined", cost:4, type:"unit", l:[3,3], d:[3,3], ability:"twin",
    text:"Twin: on play (living), its reflection falls into your dead hand.",
    art:{l:"twin sisters back to back, one in white one in grey, holding hands",
         d:"two ghostly figures merged at the shoulder into one being, serene"}},
  vb_glutton:  {rarity:"rare", name:"Grave Glutton", deadName:"Everhungry", cost:4, type:"unit", l:[3,3], d:[3,3], ability:"consume",
    text:"Consume: on play (dead), eats the weakest friendly dead unit and gains its ATK.",
    art:{l:"a corpulent ghoul licking its fingers beside an opened grave",
         d:"a vast mouth of a creature made of graves, swallowing a small ghost"}},
  vb_bellringer:{rarity:"rare", name:"Bellringer", deadName:"Knell Spirit", cost:3, type:"unit", l:[2,3], d:[1,1], deadForm:"situation",
    text:"Its dead face is a situation — deploy it from your dead hand as an omen.",
    deadFace:{name:"Knell Spirit", text:"At the start of your turn, the enemy loses 1 Soul (Life if shattered).", sitFx:{kind:"turnDrain", n:1}},
    art:{l:"a bellringer hauling on a great rope in a stone tower, bell blurred with motion",
         d:"a spectral bell with a ghost coiled around it as the clapper"}},
  vb_bloodknight:{rarity:"rare", name:"Blood-Sworn Knight", deadName:"Oathwraith", cost:0, blood:5, type:"unit", l:[3,3], d:[3,3],
    text:"Bloodprice 5: pay Life (living) or Soul (dead) instead of energy.",
    art:{l:"a knight in crimson-lacquered armor cutting his palm over his sword",
         d:"a wraith in shattered crimson armor, oath-script glowing on the blade"}},
  vb_smuggler: {rarity:"rare", name:"Veil Smuggler", deadName:"Contraband Ghost", cost:3, type:"unit", l:[2,3], d:[2,3], ability:"twin",
    text:"Twin: on play (living), its reflection falls into your dead hand.",
    art:{l:"a smuggler with a coat full of glowing vials slipping through a torn veil",
         d:"a grinning ghost carrying a sack that leaks tiny stars"}},
  vb_widow:    {rarity:"rare", name:"Widow of the Fen", deadName:"The Drowned Bride", cost:4, type:"unit", l:[2,5], d:[4,3],
    text:"She waited. She is still waiting.",
    art:{l:"a widow in black lace standing at the fen's edge holding dead flowers",
         d:"a drowned bride floating beneath dark water, veil spread wide, eyes open"}},
  vb_impaler:  {rarity:"rare", name:"Impaler", deadName:"Spike Wraith", cost:4, type:"unit", l:[4,2], d:[3,2], harvest:1,
    text:"Harvest 1: when this kills a unit, drain 1 Soul.",
    art:{l:"a grim soldier planting a long barbed spear, field of stakes behind",
         d:"a wraith bristling with spectral spikes like a broken cage"}},
  vb_warhulk:  {rarity:"rare", name:"Ossuary Hulk", deadName:"Reliquary Golem", cost:5, type:"unit", l:[3,6], d:[4,5], ability:"guard",
    text:"Guard: enemies in its dimension must attack this first.",
    art:{l:"a hulking construct of stacked ossuary boxes and chains lumbering forward",
         d:"a golem of golden reliquaries and saint bones glowing from within"}},
  vb_falconer: {rarity:"rare", name:"Ghost Falconer", deadName:"Falcon of Mist", cost:3, type:"unit", l:[3,2], d:[2,2], ability:"haste",
    text:"Haste: attacks immediately, in either dimension.",
    art:{l:"a falconer releasing a pale falcon into a storm-grey sky",
         d:"a falcon made of coiling mist diving with talons of light"}},
  vb_gorger:   {rarity:"rare", name:"Soul Gorger", deadName:"Gorged Horror", cost:5, type:"unit", l:[4,4], d:[4,4], ability:"consume",
    text:"Consume: on play (dead), eats the weakest friendly dead unit and gains its ATK.",
    art:{l:"a hunched giant with a distended glowing belly full of faint lights",
         d:"a horror stitched from many bodies, mouths open in every direction"}},
  vb_priestess:{rarity:"rare", name:"Veil Priestess", deadName:"Priestess Unveiled", cost:4, type:"unit", l:[2,4], d:[3,4], ability:"spirit",
    text:"On play: put a 2/2 Spirit into the OTHER dimension's field.",
    art:{l:"a priestess in layered veils raising a censer that bleeds silver smoke",
         d:"the priestess unveiled — her face a soft light, veils floating free"}},
  vb_drowner:  {rarity:"rare", name:"The Drowner", deadName:"Undertow", cost:4, type:"unit", l:[3,4], d:[4,3],
    text:"The river keeps what it is given.",
    art:{l:"a broad-shouldered man waist-deep in a river, holding something under",
         d:"a current of grasping pale hands beneath the water's surface"}},
  vb_naiad:    {rarity:"rare", name:"Cold Naiad", deadName:"Ice Wisp", cost:2, type:"unit", l:[2,2], d:[2,2], ability:"haste",
    text:"Haste: attacks immediately, in either dimension.",
    art:{l:"a naiad of dark water rising from a frozen pool, hair of frost",
         d:"a spinning wisp of ice crystals with a cold blue core"}},
  vb_gatekeeper:{rarity:"rare", name:"Gatekeeper of Dusk", deadName:"Gate Wraith", cost:5, type:"unit", l:[2,7], d:[3,6], ability:"guard",
    text:"Guard: enemies in its dimension must attack this first.",
    art:{l:"an armored gatekeeper before a massive dusk-lit gate, spear planted",
         d:"a wraith fused into the bars of a spectral gate, arms outstretched"}},
  vb_herald:   {rarity:"rare", name:"Herald of Ash", deadName:"Ash Harbinger", cost:4, type:"unit", l:[3,3], d:[3,3], ability:"plague",
    text:"On death: deal 1 damage to all enemy units in its dimension.",
    art:{l:"a rider on a grey horse scattering handfuls of ash as proclamation",
         d:"a harbinger of swirling ash with a burning scroll"}},

  vb_archer:   {rarity:"rare", name:"Fen Archer", deadName:"Bone Archer", cost:3, type:"unit", l:[2,2], d:[2,1], ranged:true,
    text:"Ranged: takes no retaliation when attacking units.",
    art:{l:"a hooded archer loosing an arrow from a reed blind in the fen, mist rising",
         d:"a skeletal archer drawing a bow of rib and sinew, arrow of pale light"}},

  /* ---------------- UNITS · epics ---------------- */
  vb_matriarch:{rarity:"epic", name:"Bloodline Matriarch", deadName:"Ancestor Spirit", cost:0, blood:7, type:"unit", l:[4,4], d:[4,4],
    text:"Bloodprice 7: pay Life (living) or Soul (dead) instead of energy.",
    art:{l:"a regal matriarch on an iron throne, a chalice of blood at her hand",
         d:"a vast ancestral spirit with a hundred faint family faces in her gown"}},
  vb_puppeteer:{rarity:"epic", name:"Puppeteer", deadName:"String Wraith", cost:5, type:"unit", l:[3,4], d:[1,1], deadForm:"situation",
    text:"Its dead face is a situation — deploy it from your dead hand as an omen.",
    deadFace:{name:"String Wraith", text:"Enemy dead units have −1 ATK.", sitFx:{kind:"foeDeadAtk", n:-1}},
    art:{l:"a sinister puppeteer working marionettes of soldiers on a small stage",
         d:"hundreds of glowing puppet strings descending from darkness, tugging"}},
  vb_leviathan:{rarity:"epic", name:"Fen Leviathan", deadName:"Leviathan Bones", cost:6, type:"unit", l:[5,6], d:[6,5],
    text:"The fen is its footprint.",
    art:{l:"a colossal leviathan surfacing from a fen, trees sliding off its back",
         d:"a mountain-ridge of leviathan bones with will-o-wisps in the ribs"}},
  vb_apprentice:{rarity:"epic", name:"Reaper's Apprentice", deadName:"Journeyman Death", cost:4, type:"unit", l:[3,3], d:[3,3], harvest:2,
    text:"Harvest 2: when this kills a unit, drain 2 Soul.",
    art:{l:"a nervous apprentice holding a scythe too big for him, notes in hand",
         d:"a young death in an ill-fitting robe, scythe now weightless"}},
  vb_prodigy:  {rarity:"epic", name:"Veilborn Prodigy", deadName:"Prodigy Unbound", cost:3, type:"unit", l:[2,3], d:[3,2], ability:"twin",
    text:"Twin: on play (living), its reflection falls into your dead hand.",
    art:{l:"a young mage with mismatched eyes, one hand in this world one in another",
         d:"the prodigy split into light and dark halves, both smiling"}},
  vb_saint:    {rarity:"epic", name:"Saint of Embers", deadName:"Ember Saint", cost:4, type:"unit", l:[3,4], d:[2,2], ability:"undying",
    text:"Undying: when this dies, it returns to that dimension's hand instead of passing on.",
    art:{l:"a haloed saint wreathed in gentle embers, palms open",
         d:"the saint as a figure of cooling embers, halo of smoke"}},
  vb_count:    {rarity:"epic", name:"Hollow Count", deadName:"Count of Teeth", cost:5, type:"unit", l:[4,5], d:[3,5], ability:"consume",
    text:"Consume: on play (dead), eats the weakest friendly dead unit and gains its ATK.",
    art:{l:"an elegant hollow-eyed count in a high collar, wine glass of something dark",
         d:"a grinning count whose smile is far too wide and full of teeth"}},
  vb_seamwalker:{rarity:"epic", name:"Seamwalker", deadName:"Seamless One", cost:4, type:"unit", l:[3,4], d:[4,4], ability:"haste",
    text:"Haste: attacks immediately, in either dimension.",
    art:{l:"a figure stepping halfway through a glowing seam in the air, one boot in each world",
         d:"a smooth faceless being whose outline ripples like disturbed water"}},
  vb_titan:    {rarity:"epic", name:"Barrow Titan", deadName:"Titan of Sorrow", cost:7, type:"unit", l:[6,7], d:[7,6],
    text:"Hills are just titans who lay down.",
    art:{l:"a titan of earth and barrow-stones rising, ancient swords stuck in its back",
         d:"a weeping titan of shadow, tears of pale light carving canyons"}},
  vb_confessor:{rarity:"epic", name:"Confessor", deadName:"Secret Eater", cost:4, type:"unit", l:[3,4], d:[2,3], ability:"heal2",
    text:"On play: restore 2 Life — or 2 Soul if played dead.",
    art:{l:"a confessor behind a carved screen, ear turned to a shadow",
         d:"a creature of black robes swallowing glowing whispered words"}},
  vb_chained:  {rarity:"epic", name:"The Chained One", deadName:"Unchained", cost:6, type:"unit", l:[1,9], d:[6,4], ability:"guard",
    text:"Guard: enemies in its dimension must attack this first.",
    art:{l:"a massive figure wrapped entirely in chains and holy seals, kneeling",
         d:"the same figure standing free, chains floating broken around it"}},
  vb_lamplord: {rarity:"epic", name:"Lord of Lamps", deadName:"Lantern Sovereign", cost:5, type:"unit", l:[4,4], d:[1,1], deadForm:"situation",
    text:"Its dead face is a situation — deploy it from your dead hand as an omen.",
    deadFace:{name:"Lantern Sovereign", text:"Your units enter the dead field with +1 HP.", sitFx:{kind:"enterDeadHp", n:1}},
    art:{l:"a noble draped in dozens of small brass lamps, each with a different flame",
         d:"a constellation of floating lanterns arranged like a crowned figure"}},

  vb_ballista: {rarity:"epic", name:"Grave Ballista", deadName:"Ghost Ballista", cost:5, type:"unit", l:[4,3], d:[3,3], ranged:true,
    text:"Ranged: takes no retaliation when attacking units.",
    art:{l:"a siege ballista built from coffin planks and iron, crew winching it back",
         d:"a translucent ballista of pale light firing a bolt of mist"}},

  /* ---------------- UNITS · legendaries ---------------- */
  vb_bloodgod: {rarity:"legendary", name:"Vharu, Who Thirsts", deadName:"Vharu, Sated", cost:0, blood:8, type:"unit", l:[5,5], d:[5,5], harvest:2,
    text:"Bloodprice 8. Harvest 2: kills drain 2 Soul.",
    art:{l:"a towering blood god with a cracked stone face and rivers of red down its arms",
         d:"the god at rest, face whole, red rivers now still and black"}},
  vb_echoqueen:{rarity:"legendary", name:"Queen of Echoes", deadName:"The Echo Herself", cost:6, type:"unit", l:[4,5], d:[5,4], ability:"twin",
    text:"Twin: on play (living), its reflection falls into your dead hand.",
    art:{l:"a queen whose reflection in every mirror behind her moves differently",
         d:"a queen made of overlapping translucent after-images, crown ringing"}},
  vb_gatewarden:{rarity:"legendary", name:"Warden of Both Gates", deadName:"The Gate Itself", cost:7, type:"unit", l:[3,8], d:[5,7], ability:"guard",
    text:"Guard: enemies in its dimension must attack this first.",
    art:{l:"a two-faced warden standing between a white gate and a black gate, keys crossed",
         d:"a living gate of bone and gold, its doors slightly open onto stars"}},
  vb_wispmother:{rarity:"legendary", name:"Wispmother", deadName:"Mother of Hundreds", cost:6, type:"unit", l:[3,6], d:[4,6], ability:"spirit",
    text:"On play: put a 2/2 Spirit into the OTHER dimension's field.",
    art:{l:"a gentle giantess with dozens of tiny wisps sheltering in her hair",
         d:"a vast maternal shade opening her cloak to release a hundred wisps"}},

  /* ---------------- SPELLS · commons ---------------- */
  vb_spark:    {rarity:"common", name:"Veil Spark", cost:1, type:"spell", target:"anyLiving", fx:{kind:"dmg", n:2},
    text:"Deal 2 damage to any living unit.",
    deadFace:{name:"Grave Spark", target:"anyDead", fx:{kind:"dmg", n:2}, text:"Deal 2 damage to any dead unit."},
    art:{l:"a single crackling spark of golden lightning arcing between two fingers",
         d:"a violet spark jumping between two gravestones"}},
  vb_alms:     {rarity:"common", name:"Alms", cost:1, type:"spell", fx:{kind:"healLife", n:2},
    text:"Restore 2 Life.",
    deadFace:{name:"Ghost Alms", fx:{kind:"healSoul", n:2}, text:"Restore 2 Soul (Life if shattered)."},
    art:{l:"weathered hands dropping bread and coins into a beggar's bowl",
         d:"a ghostly hand dropping glowing coins through a bowl into nothing"}},
  vb_shove:    {rarity:"common", name:"Rude Awakening", cost:1, type:"spell", target:"friendlyLiving", fx:{kind:"buff", a:1, h:1},
    text:"A friendly living unit gains +1/+1.",
    deadFace:{name:"Cold Awakening", target:"friendlyDeadAny", fx:{kind:"buff", a:1, h:1}, text:"A friendly dead unit gains +1/+1."},
    art:{l:"a soldier being shaken awake at dawn, grabbing his spear",
         d:"a corpse's eyes snapping open with pale light"}},
  vb_scavenge: {rarity:"common", name:"Scavenge", cost:1, type:"spell", fx:{kind:"draw", n:1},
    text:"Draw a card.",
    deadFace:{name:"Grave Scavenge", fx:{kind:"draw", n:1}, text:"Draw a card."},
    art:{l:"a gloved hand pulling a glinting trinket from battlefield mud",
         d:"a skeletal hand offering up a card of light from below the soil"}},
  vb_bolt:     {rarity:"common", name:"Marsh Bolt", cost:2, type:"spell", target:"anyLiving", fx:{kind:"dmg", n:3},
    text:"Deal 3 damage to any living unit.",
    deadFace:{name:"Sorrow Bolt", fx:{kind:"drainSoul", n:2}, text:"Drain 2 Soul from the enemy."},
    art:{l:"a green-white bolt of marsh lightning splitting a dead tree",
         d:"a slow dark bolt of sorrow arcing into a kneeling silhouette"}},
  vb_tithe:    {rarity:"common", name:"Tithe", cost:0, type:"spell", fx:{kind:"drainSoul", n:1},
    text:"Drain 1 Soul from the enemy.",
    deadFace:{name:"Death Tithe", fx:{kind:"drainLife", n:1}, text:"Drain 1 Life from the enemy."},
    art:{l:"a collection plate of dull coins with one glowing soul-mote among them",
         d:"a bone hand taking a single glowing coin from a sleeping man's chest"}},
  vb_fog:      {rarity:"common", name:"Veilfog", cost:2, type:"spell", fx:{kind:"aoe", n:1},
    text:"Deal 1 damage to ALL living units — yours too.",
    deadFace:{name:"Gravefog", fx:{kind:"aoe", n:1}, text:"Deal 1 damage to ALL dead units — yours too."},
    art:{l:"a choking silver fog rolling over an army's boots",
         d:"a low violet fog seeping between tombstones, faces in it"}},
  vb_pin:      {rarity:"common", name:"Pin of Light", cost:1, type:"spell", target:"anyLiving", fx:{kind:"dmg", n:1}, echo:true,
    text:"Deal 1 damage. Echo: a copy slips into your dead hand.",
    deadFace:{name:"Pin of Shadow", target:"anyDead", fx:{kind:"dmg", n:1}, text:"Deal 1 damage to any dead unit."},
    art:{l:"a needle of pure light pinning a shadow to the wall",
         d:"a needle of shadow pinning a small light to the floor"}},
  vb_rations:  {rarity:"common", name:"Cold Rations", cost:1, type:"spell", fx:{kind:"healSoul", n:2},
    text:"Restore 2 Soul (Life if shattered).",
    deadFace:{name:"Last Rations", fx:{kind:"healLife", n:2}, text:"Restore 2 Life."},
    art:{l:"a tin plate of grey bread and salt fish on a frosty windowsill",
         d:"an empty tin plate set at a grave, licked clean"}},
  vb_whetstone:{rarity:"common", name:"Whetstone", cost:1, type:"spell", target:"friendlyLiving", fx:{kind:"buff", a:2, h:0},
    text:"A friendly living unit gains +2 ATK.",
    deadFace:{name:"Bone Whet", target:"friendlyDeadAny", fx:{kind:"buff", a:2, h:0}, text:"A friendly dead unit gains +2 ATK."},
    art:{l:"sparks flying as a blade is drawn hard across a whetstone",
         d:"a claw being sharpened against a jawbone"}},

  /* ---------------- SPELLS · rares ---------------- */
  vb_lash:     {rarity:"rare", name:"Soul Lash", cost:3, type:"spell", fx:{kind:"drainSoul", n:3},
    text:"Drain 3 Soul from the enemy.",
    deadFace:{name:"Life Lash", fx:{kind:"drainLife", n:3}, text:"Drain 3 Life from the enemy."},
    art:{l:"a whip of braided pale light cracking across a battlefield",
         d:"a whip of red sinew cracking through the veil itself"}},
  vb_veilshift:{rarity:"rare", name:"Veilshift", cost:2, type:"spell", target:"friendlyLiving", fx:{kind:"shift"},
    text:"A friendly living unit steps through the veil and becomes its dead face.",
    deadFace:{name:"Veilreturn", target:"friendlyDead", fx:{kind:"shift"}, text:"A friendly dead unit steps back through and becomes its living face."},
    art:{l:"a soldier mid-step through a rippling curtain of silver light, half transformed",
         d:"a ghost stepping out of the curtain, color returning to its edges"}},
  vb_gamble:   {rarity:"rare", name:"Grave Gamble", cost:2, type:"spell", fx:{kind:"gamble"},
    text:"Reveal your top card: a unit storms in free — anything else falls to your dead hand.",
    deadFace:{name:"Double Down", fx:{kind:"gamble"}, text:"Reveal your top card: a unit storms into the dead — anything else falls to your dead hand."},
    art:{l:"dice carved from knucklebones tumbling across a coffin lid",
         d:"a skeleton palming two dice, grinning at an unseen opponent"}},
  vb_echobolt: {rarity:"rare", name:"Echoing Bolt", cost:3, type:"spell", target:"anyLiving", fx:{kind:"dmg", n:3}, echo:true,
    text:"Deal 3 damage. Echo: a copy slips into your dead hand.",
    deadFace:{name:"Bolt Remembered", target:"anyDead", fx:{kind:"dmg", n:3}, text:"Deal 3 damage to any dead unit."},
    art:{l:"a lightning bolt striking twice in the exact same place, afterimage hanging",
         d:"the memory of a lightning bolt, frozen violet in the air"}},
  vb_cauterize:{rarity:"rare", name:"Cauterize", cost:2, type:"spell", fx:{kind:"cauterize", n:4},
    text:"Restore 4 Life — excess healing sears the enemy's Life.",
    deadFace:{name:"Soul Brand", fx:{kind:"healSoul", n:3}, text:"Restore 3 Soul (Life if shattered)."},
    art:{l:"a glowing iron pressed to a wound, steam and golden light",
         d:"a brand of light pressed onto a shadowy chest, hissing"}},
  vb_index:    {rarity:"rare", name:"Forbidden Index", cost:3, type:"spell", fx:{kind:"draw", n:3, payLife:3},
    text:"Draw 3 cards. Lose 3 Life.",
    deadFace:{name:"Index of the Dead", fx:{kind:"draw", n:3, paySoul:3}, text:"Draw 3 cards. Lose 3 Soul (Life if shattered)."},
    art:{l:"a black-bound index whose page corners are stained with fingerprints of blood",
         d:"a card catalogue of tiny coffins, one drawer open and glowing"}},
  vb_hush:     {rarity:"rare", name:"Hush", cost:2, type:"spell", target:"situationLiving", fx:{kind:"dispel"},
    text:"Destroy an enemy situation over the living dimension.",
    deadFace:{name:"Deafen", target:"situationDead", fx:{kind:"dispel"}, text:"Destroy an enemy situation over the dead dimension."},
    art:{l:"a finger pressed to lips, sound visibly dying around it in ripples",
         d:"two hands clamped over the ears of a screaming stone gargoyle"}},
  vb_flay:     {rarity:"rare", name:"Flay", cost:4, type:"spell", target:"anyLiving", fx:{kind:"dmg", n:5},
    text:"Deal 5 damage to any living unit.",
    deadFace:{name:"Unmake", target:"anyDead", fx:{kind:"dmg", n:5}, text:"Deal 5 damage to any dead unit."},
    art:{l:"ribbons of red light peeling away from a struck warrior",
         d:"a ghost coming apart into loose threads of pale light"}},
  vb_muster:   {rarity:"rare", name:"Muster at Dusk", cost:2, type:"spell", fx:{kind:"gainEss", n:3},
    text:"Gain 3 Essence this turn.",
    deadFace:{name:"Muster at Midnight", fx:{kind:"gainDeadEss", n:3}, text:"Gain 3 dead energy this turn."},
    art:{l:"soldiers gathering on a hill at dusk, spears black against orange sky",
         d:"ghosts assembling in ranks under a black midnight sky"}},

  /* ---------------- SPELLS · epics ---------------- */
  vb_ashstorm: {rarity:"epic", name:"Ashstorm", cost:5, type:"spell", fx:{kind:"aoe", n:3},
    text:"Deal 3 damage to ALL living units — yours too.",
    deadFace:{name:"Soulstorm", fx:{kind:"aoe", n:3}, text:"Deal 3 damage to ALL dead units — yours too."},
    art:{l:"a hurricane of burning ash engulfing an army, banners aflame",
         d:"a vortex of screaming pale souls tearing across a grave-field"}},
  vb_greatecho:{rarity:"epic", name:"The Great Echo", cost:4, type:"spell", fx:{kind:"draw", n:2}, echo:true,
    text:"Draw 2 cards. Echo: a copy slips into your dead hand.",
    deadFace:{name:"The Last Echo", fx:{kind:"draw", n:2}, text:"Draw 2 cards."},
    art:{l:"a shout visualized as golden rings expanding through a canyon of statues",
         d:"the same rings, now violet, collapsing inward to a single point"}},
  vb_transfuse:{rarity:"epic", name:"Transfusion", cost:3, type:"spell", fx:{kind:"cauterize", n:6},
    text:"Restore 6 Life — excess healing sears the enemy's Life.",
    deadFace:{name:"Soul Graft", fx:{kind:"healSoul", n:4}, text:"Restore 4 Soul (Life if shattered)."},
    art:{l:"light flowing through a crystal tube from a saint's arm into a soldier's",
         d:"a shimmering patch of borrowed soul being pressed onto a cracked spirit"}},
  vb_blessing: {rarity:"epic", name:"Blessing of Both Worlds", cost:4, type:"spell", target:"friendlyLiving", fx:{kind:"buff", a:2, h:2}, echo:true,
    text:"A friendly living unit gains +2/+2. Echo: a copy slips into your dead hand.",
    deadFace:{name:"Curse of Neither", target:"friendlyDeadAny", fx:{kind:"buff", a:2, h:2}, text:"A friendly dead unit gains +2/+2."},
    art:{l:"two hands, one of light and one of shadow, resting on a knight's shoulders",
         d:"a figure blessed by neither world, glowing seams where the hands touched"}},
  vb_ruin:     {rarity:"epic", name:"Word of Ruin", cost:6, type:"spell", fx:{kind:"aoe", n:4},
    text:"Deal 4 damage to ALL living units — yours too.",
    deadFace:{name:"Word of Dust", fx:{kind:"aoe", n:4}, text:"Deal 4 damage to ALL dead units — yours too."},
    art:{l:"a single spoken word cracking the earth in a widening ring",
         d:"a word of dust dissolving a row of ghosts like wind over sand"}},

  /* ---------------- SPELLS · legendary ---------------- */
  vb_apocrypha:{rarity:"legendary", name:"Apocrypha", cost:5, type:"spell", fx:{kind:"draw", n:3}, echo:true,
    text:"Draw 3 cards. Echo: a copy slips into your dead hand.",
    deadFace:{name:"The Last Page", fx:{kind:"draw", n:3}, text:"Draw 3 cards."},
    art:{l:"a forbidden gospel opening itself, pages turning in no wind",
         d:"the final page of a burned book, its words floating free as ash"}},

  /* ---------------- SITUATIONS ---------------- */
  vb_shrine:   {rarity:"common", name:"Roadside Shrine", deadName:"Defiled Shrine", cost:1, type:"situation",
    text:"At the start of your turn, restore 1 Life.", sitFx:{kind:"turnLife", n:1},
    deadFace:{name:"Defiled Shrine", text:"At the start of your turn, restore 1 Soul (Life if shattered).", sitFx:{kind:"turnSoul", n:1}},
    art:{l:"a small roadside shrine with fresh flowers and a burning candle",
         d:"the same shrine toppled and moss-eaten, candle burning violet"}},
  vb_stakes:   {rarity:"common", name:"Field of Stakes", deadName:"Field of Wails", cost:2, type:"situation",
    text:"Enemy units that attack your hero in the living dimension take 1 damage.", sitFx:{kind:"ward", n:1},
    deadFace:{name:"Field of Wails", text:"Enemy units that attack your hero in the dead dimension take 1 damage.", sitFx:{kind:"ward", n:1}},
    art:{l:"a defensive field of sharpened stakes silhouetted at sunset",
         d:"a field of translucent howling faces planted like stakes"}},
  vb_beacon:   {rarity:"common", name:"Dusk Beacon", deadName:"Grave Beacon", cost:2, type:"situation",
    text:"At the start of your turn, gain 1 extra Essence. Burns out after 5 turns.", sitFx:{kind:"turnEss", n:1, charges:5},
    deadFace:{name:"Grave Beacon", text:"At the start of your turn, gain 1 dead energy. Burns out after 5 turns.", sitFx:{kind:"turnDeadEss", n:1, charges:5}},
    art:{l:"a hilltop beacon of orange flame against a deep dusk sky",
         d:"a cold green beacon burning on a barrow mound"}},
  vb_garden:   {rarity:"common", name:"Bone Garden", deadName:"Garden in Bloom", cost:2, type:"situation",
    text:"Whenever one of your living units dies, restore 1 Life.", sitFx:{kind:"onLivingDeathLife", n:1},
    deadFace:{name:"Garden in Bloom", text:"Your units enter the dead field with +1 HP.", sitFx:{kind:"enterDeadHp", n:1}},
    art:{l:"a garden bed where finger bones sprout like white crocuses",
         d:"the garden in full bloom — flowers of bone and pale light"}},
  vb_millstone:{rarity:"common", name:"Millstone", deadName:"Grindstone of Souls", cost:2, type:"situation",
    text:"At the start of your turn, draw an extra card. Burns out after 3 turns.", sitFx:{kind:"turnDraw", n:1, charges:3},
    deadFace:{name:"Grindstone of Souls", text:"At the start of your turn, gain 2 dead energy. Burns out after 3 turns.", sitFx:{kind:"turnDeadEss", n:2, charges:3}},
    art:{l:"a heavy millstone turning slowly, grain and folded letters ground together",
         d:"a grindstone milling faint lights into glittering dust"}},
  vb_candles:  {rarity:"common", name:"Row of Candles", deadName:"Row of Wisps", cost:1, type:"situation",
    text:"At the start of your turn, restore 1 Soul (Life if shattered).", sitFx:{kind:"turnSoul", n:1},
    deadFace:{name:"Row of Wisps", text:"At the start of your turn, restore 1 Soul (Life if shattered).", sitFx:{kind:"turnSoul", n:1}},
    art:{l:"a long row of votive candles in red glass, one freshly lit",
         d:"a row of hovering wisps where the candles used to stand"}},
  vb_drums:    {rarity:"rare", name:"March Drums", deadName:"Death March", cost:3, type:"situation",
    text:"Your living units have +1 ATK.", sitFx:{kind:"livingAtk", n:1},
    deadFace:{name:"Death March", text:"Your dead units have +1 ATK.", sitFx:{kind:"deadAtk", n:1}},
    art:{l:"regimental drums and banners on the march at first light",
         d:"a skeletal drum line marching through mist, sticks of bone"}},
  vb_tollbooth:{rarity:"rare", name:"Veil Tollbooth", deadName:"Toll of Bone", cost:3, type:"situation",
    text:"At the start of your turn, the enemy loses 1 Soul (Life if shattered).", sitFx:{kind:"turnDrain", n:1},
    deadFace:{name:"Toll of Bone", text:"At the start of your turn, the enemy loses 1 Soul (Life if shattered).", sitFx:{kind:"turnDrain", n:1}},
    art:{l:"a tollbooth built into the veil itself, a queue of souls paying passage",
         d:"a booth of stacked bones where a skeletal hand collects glowing coins"}},
  vb_lighthouse:{rarity:"rare", name:"Far Lighthouse", deadName:"Drowned Light", cost:3, type:"situation",
    text:"At the start of your turn, draw an extra card. Burns out after 4 turns.", sitFx:{kind:"turnDraw", n:1, charges:4},
    deadFace:{name:"Drowned Light", text:"Enemy dead units have −1 ATK.", sitFx:{kind:"foeDeadAtk", n:-1}},
    art:{l:"a distant lighthouse sweeping its beam across a black sea",
         d:"a lighthouse fully underwater, beam still turning through the deep"}},
  vb_abattoir: {rarity:"rare", name:"Abattoir", deadName:"Charnel House", cost:3, type:"situation",
    text:"Whenever one of your living units dies, restore 2 Life.", sitFx:{kind:"onLivingDeathLife", n:2},
    deadFace:{name:"Charnel House", text:"Whenever one of your dead units is destroyed, the enemy loses 2 Soul (Life if shattered).", sitFx:{kind:"onDeadDestroyDrain", n:2}},
    art:{l:"a grim abattoir doorway, hooks and chains, sawdust floor",
         d:"a charnel house stacked with candles and skulls, oddly reverent"}},
  vb_fountain: {rarity:"rare", name:"Blood Fountain", deadName:"Ichor Fountain", cost:0, blood:3, type:"situation",
    text:"Bloodprice 3. At the start of your turn, restore 1 Life.", sitFx:{kind:"turnLife", n:1},
    deadFace:{name:"Ichor Fountain", text:"At the start of your turn, restore 2 Soul (Life if shattered).", sitFx:{kind:"turnSoul", n:2}},
    art:{l:"a marble fountain running red under a waning moon",
         d:"a black fountain running with luminous silver ichor"}},
  vb_longwatch:{rarity:"rare", name:"The Long Watch", deadName:"The Longer Watch", cost:2, type:"situation",
    text:"At the start of your turn, gain 1 dead energy.", sitFx:{kind:"turnDeadEss", n:1},
    deadFace:{name:"The Longer Watch", text:"At the start of your turn, gain 1 extra Essence.", sitFx:{kind:"turnEss", n:1}},
    art:{l:"a sentry's brazier burning on a wall at 3am, frost on the stones",
         d:"a ghost sentry saluting the sunrise it can no longer see"}},
  vb_tolling:  {rarity:"epic", name:"The Tolling", deadName:"The Last Toll", cost:4, type:"situation",
    text:"Tolls each turn. On the third knell: every LIVING unit dies.", sitFx:{kind:"doom", n:3},
    deadFace:{name:"The Last Toll", text:"Tolls each turn. On the third knell: every DEAD unit is destroyed.", sitFx:{kind:"doom", n:3}},
    art:{l:"a cathedral bell the size of a house, rope descending into darkness",
         d:"a cracked black bell hanging over a field of open graves"}},
  vb_mirror:   {rarity:"epic", name:"Mirror of Sorrows", deadName:"Mirror, Cracked", cost:4, type:"situation",
    text:"At the start of your turn, draw an extra card.", sitFx:{kind:"turnDraw", n:1},
    deadFace:{name:"Mirror, Cracked", text:"At the start of your turn, draw an extra card.", sitFx:{kind:"turnDraw", n:1}},
    art:{l:"an ornate standing mirror reflecting a room that is not this one",
         d:"the mirror cracked, each shard showing a different weeping face"}},
  vb_furnace:  {rarity:"epic", name:"Soul Furnace", deadName:"Furnace of Night", cost:4, type:"situation",
    text:"At the start of your turn, gain 2 extra Essence.", sitFx:{kind:"turnEss", n:2},
    deadFace:{name:"Furnace of Night", text:"At the start of your turn, gain 2 dead energy.", sitFx:{kind:"turnDeadEss", n:2}},
    art:{l:"an industrial furnace glowing white-blue, fed with glowing motes",
         d:"a cold furnace burning black flame that casts shadow instead of light"}},
  vb_veilcrown:{rarity:"legendary", name:"Crown of the Veil", deadName:"Crown, Inverted", cost:5, type:"situation",
    text:"Your living units have +2 ATK.", sitFx:{kind:"livingAtk", n:2},
    deadFace:{name:"Crown, Inverted", text:"Your dead units have +2 ATK.", sitFx:{kind:"deadAtk", n:2}},
    art:{l:"a floating golden crown ringed with living green flame",
         d:"the crown upside down, black metal ringed with violet flame"}},
};

Object.assign(DEFS, VEILBOUND);
